[project]
name = "qa_automation_team"
version = "0.1.0"
description = "qa_automation_team using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.3.0"
]

[project.scripts]
qa_automation_team = "qa_automation_team.main:run"
run_crew = "qa_automation_team.main:run"
train = "qa_automation_team.main:train"
replay = "qa_automation_team.main:replay"
test = "qa_automation_team.main:test"
run_with_trigger = "qa_automation_team.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
