find_emerging_companies:
  description: >
    Find the top trending companies in the news in {sector} by searching the latest news.
    Find new companies that you have not found before.
  expected_output: >
    A list of trending companies in {sector}
  agent: emerging_companies_finder
  output_file: output/trending_companies.json



reserach_emerging_companies:
  description: >
    Given a list of trending companies, provide detailed analysis of each company in a report by searching online
  expected_output: >
    A report containing detailed analysis of each company
  agent: financial_researcher
  context: 
    - find_emerging_companies
  output_file: output/research_report.json



pick_best_companies:
  description: >
    Analyze the research findings and pick the best company for investment.
    Send a push notification to the user with the decision and 1 sentence rationale.
    Then respond with a detailed report on why you chose this company, and which companies were not selected.
  expected_output: >
    The chosen company and why it was chosen; the companies that were not selected and why they were not selected.
  agent: stock_picker
  context: find_emerging_companies
  output_file: output/decision.md


  
  













research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
